name: Main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    env:
      COCKPIT_API_URL: ${{secrets.COCKPIT_API_URL}}
      COCKPIT_BASE_URL: ${{secrets.COCKPIT_BASE_URL}}
      COCKPIT_API_TOKEN: ${{secrets.COCKPIT_API_TOKEN}}
      AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn deploy