name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn build