name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    env:
      COCKPIT_API_URL: ${{secrets.COCKPIT_API_URL}}
      COCKPIT_BASE_URL: ${{secrets.COCKPIT_BASE_URL}}
      COCKPIT_API_TOKEN: ${{secrets.COCKPIT_API_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.elm
            **/elm-stuff
            **/.cache
          key: ${{ runner.os }}-elm-stuff-${{ hashFiles('**/elm.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Sync Content
        run: yarn sync
      - name: Build Application
        run: yarn build
      - name: Run Tests
        run: yarn test